### ISSUE TITLE
Directory not found

### ISSUE THREAD

**Issue by EderSantana** [carpedm20/MemN2N-tensorflow#3]
Hi, thanks for the code.

I'm getting the following error when running main

```
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    tf.app.run()
  File "/home/eders/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    tf.app.run()
  File "/home/eders/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 43, in main
    model = MemN2N(FLAGS, sess)
  File "/home/eders/python/MemN2N-tensorflow/model.py", line 26, in __init__
    raise Exception(" [!] Directory %s not found" % self.checkpoint_dir)
Exception:  [!] Directory checkpoints not found
```

I tried to use --data_dir but that didn't work either.

**Comment by carpedm20** [comment]
@EderSantana I should have fixed this earlier. Try pulling the code and re run it :smile:
